import type { Metadata } from 'next';
import { SessionProvider } from 'next-auth/react';
import QueryProvider from '@/providers/QueryClientProvider';
import { Inter } from 'next/font/google';
import NavBar from '@/components/NavBar';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SessionProvider>
        <QueryProvider>
          <body className={inter.className}>
            <NavBar />
            {children}
          </body>
        </QueryProvider>
      </SessionProvider>
    </html>
  );
}
